spring:
  profiles:
    group:
      "local": "local, jwt"
    active: local
    include:
      - base-addi

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:SecurityOauth2JwtDB
    path: /h2-console
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  logging:
    level:
      me.pracitce: info

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId:
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/kakao/callback
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id